### ISSUE TITLE
error on setup 

### ISSUE THREAD

**Issue by pcalder3** [boilermaker-ben/Google-NFL-Pick-Ems#2]
I get this on setup after putting in peoples names

4:46:11 PM	Info	Deployed Overall Rank sheet
4:46:17 PM	Info	Deployed Overall Percent sheet
4:46:17 PM	Info	runFirstStack TypeError: Cannot read properties of undefined (reading 'alert')
    at runFirst (Code:84:28)
    at __GS_INTERNAL_top_function_call__.gs:1:8

**Comment by pcalder3** [comment]
sorry, I see you said to wait, just and FYI for you. 
Thanks for the efforts.

**Comment by boilermaker-ben** [comment]
Hi @pcalder3 -- thanks for checking out the script. I'm not sure what exactly generated this error for you, but I'm in the process of heavily updating the script, which I hope to release in the next few days.

**Comment by pcalder3** [comment]
You just need to move this to line 84 of your code to the survivor pool
popup works.
Hope that helps.
    var ui = SpreadsheetApp.getUi();

**Comment by boilermaker-ben** [comment]
Good work figuring out what the error was. I just posted this on Reddit:
https://www.reddit.com/r/fantasyfootball/comments/167j788/run_your_own_pickems_or_survivor_group_free/

And here's the new version on GitHub:
https://github.com/boilermaker-ben/Google-Sheets-NFL-Pick-Ems-and-Survivor-Pool/

Good luck and let me know if you run into any issues!
